/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder16_38 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    input [15:0] carryOut,
    output reg [15:0] op,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [15:0] zin;
  
  always @* begin
    zin = 1'h0;
    
    case (alufn[0+1-:2])
      default: begin
        op = 1'h0;
      end
      2'h0: begin
        op = a + b;
        zin = a + b;
      end
      2'h1: begin
        op = a - b;
        zin = a + b;
      end
      2'h2: begin
        op = a * b;
        zin = a + b;
      end
    endcase
    if (zin == 16'h0000) begin
      z = 1'h1;
    end else begin
      z = 1'h0;
    end
    v = (a[15+0-:1] & (!carryOut[15+0-:1]) & (b[15+0-:1] ^ alufn[0+0-:1])) | ((!a[15+0-:1]) & carryOut[15+0-:1] & !(b[15+0-:1] ^ alufn[0+0-:1]));
    n = carryOut[15+0-:1];
  end
endmodule
