/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module bool16_41 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] op
  );
  
  
  
  always @* begin
    
    case (alufn[0+3-:4])
      default: begin
        op = 1'h0;
      end
      4'h0: begin
        op = 1'h0;
      end
      4'h6: begin
        op = a ^ b;
      end
      4'h8: begin
        op = a & b;
      end
      4'h9: begin
        op = a ~^ b;
      end
      4'ha: begin
        op = a;
      end
      4'hc: begin
        op = b;
      end
      4'he: begin
        op = a | b;
      end
    endcase
  end
endmodule
