/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare16_39 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    input z,
    input v,
    input n,
    output reg [15:0] op
  );
  
  
  
  always @* begin
    op[1+14-:15] = 1'h0;
    
    case (alufn[0+2-:3])
      3'h3: begin
        op[0+0-:1] = a == b;
      end
      3'h5: begin
        op[0+0-:1] = v ^ n;
      end
      3'h7: begin
        op[0+0-:1] = a <= b;
      end
      default: begin
        op[0+0-:1] = 1'h0;
      end
    endcase
  end
endmodule
