/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     SIZE = 5
     DIV = 26
     TOP = 30
     UP = 0
*/
module custom_counter_13 (
    input clk,
    input rst,
    output reg [4:0] value,
    output reg out,
    output reg [25:0] firstOut
  );
  
  localparam SIZE = 3'h5;
  localparam DIV = 5'h1a;
  localparam TOP = 5'h1e;
  localparam UP = 1'h0;
  
  
  reg [30:0] M_ctr_d, M_ctr_q = 31'h7fffffff;
  reg [25:0] M_rise_d, M_rise_q = 1'h0;
  
  localparam MAX_VALUE = 31'h7bffffff;
  
  always @* begin
    M_rise_d = M_rise_q;
    M_ctr_d = M_ctr_q;
    
    value = M_ctr_q[26+4-:5];
    out = ~M_rise_q[25+0-:1];
    firstOut = ~M_rise_q;
    if (1'h0) begin
      M_ctr_d = M_ctr_q + 1'h1;
      if (1'h1 && M_ctr_q == 31'h7bffffff) begin
        M_ctr_d = 1'h0;
      end
    end else begin
      M_rise_d = M_rise_q + 1'h1;
      M_ctr_d = M_ctr_q - 1'h1;
      if (1'h1 && M_ctr_q == 1'h0) begin
        M_ctr_d = 1'h0;
      end
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_ctr_q <= 31'h7fffffff;
      M_rise_q <= 1'h0;
    end else begin
      M_ctr_q <= M_ctr_d;
      M_rise_q <= M_rise_d;
    end
  end
  
endmodule
