/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shift16_41 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] op
  );
  
  
  
  always @* begin
    
    case (alufn[0+1-:2])
      default: begin
        op = 1'h0;
      end
      2'h0: begin
        op = a <<< b[0+3-:4];
      end
      2'h1: begin
        op = a >>> b[0+3-:4];
      end
      2'h3: begin
        op = $signed(a) >>> b[0+3-:4];
      end
    endcase
  end
endmodule
